version: "3.6"

services:
  app:
    tty: true
    # Node app running in port 80
    image: mariohd/my-node-image
    container_name: node-api
  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - www-certbot:/var/www/certbot
    depends_on:
      - app
  certbot:
    certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - www-certbot:/var/www/certbot
volumes:
  www-certbot:
