version: '3.7'

services:
  flask:
    # Flask app that runs in port 3031 with some wsgi package
    image: mariohd/some-flask:latest
    container_name: flask
    restart: always
  nginx:
    # Reverse proxy to nginx
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask
